# Generated by Django 3.1.5 on 2021-06-03 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Başarılar',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=25)),
                ('soyisim', models.CharField(max_length=25)),
                ('mesaj', models.TextField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='ShopProducts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('clr', 'Renk'), ('bg-img', 'Arka plan resim'), ('rights', 'Haklar')], default='Renk', max_length=15)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='my_dict/static/img')),
            ],
        ),
        migrations.CreateModel(
            name='WordDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=50)),
                ('is_in_reminder_list', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WordEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=100)),
                ('audio', models.CharField(max_length=300)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_learned', models.BooleanField(default=False)),
                ('is_seen', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_in_reminder_list', models.BooleanField(default=False)),
                ('is_new_in_reminder_list', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='WotdEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=100, null=True)),
                ('audio', models.CharField(max_length=300, null=True)),
                ('website', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WotdTr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turkish', models.CharField(max_length=100)),
                ('english', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turkish', to='my_dict.wotden')),
            ],
        ),
        migrations.CreateModel(
            name='WordTr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turkish', models.CharField(max_length=100)),
                ('english', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turkish', to='my_dict.worden')),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Aramalar',
            },
        ),
        migrations.CreateModel(
            name='QuizRecorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=100)),
                ('is_db', models.BooleanField(default=False)),
                ('is_learned', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_db_rights', models.PositiveIntegerField(default=1)),
                ('quiz_unl_rights', models.PositiveIntegerField(default=1)),
                ('quiz_l_rights', models.PositiveIntegerField(default=1)),
                ('open_reminder_daily', models.BooleanField(default=False)),
                ('reminder_count', models.IntegerField(default=0)),
                ('coin', models.IntegerField(default=0)),
                ('custom_navbar_color', models.CharField(blank=True, default='teal', max_length=100, null=True)),
                ('custom_background_color', models.CharField(blank=True, default='teal', max_length=100, null=True)),
                ('custom_background_image', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(default='')),
                ('type', models.CharField(default='', max_length=30)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('background_image', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_dict.profile')),
            ],
        ),
        migrations.CreateModel(
            name='AchievementTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achiev_no', models.IntegerField(default=0)),
                ('progress_current', models.PositiveIntegerField(default=0)),
                ('progress_star', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_dict.profile')),
            ],
        ),
        migrations.CreateModel(
            name='AchievementDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250)),
                ('coin_value', models.IntegerField(default=0)),
                ('is_daily', models.BooleanField(default=False)),
                ('achiev_no', models.IntegerField(default=0)),
                ('progress_max', models.IntegerField(default=0)),
                ('ach_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='my_dict.achievements')),
            ],
        ),
    ]
