# Generated by Django 3.1.4 on 2020-12-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0003_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
            ],
        ),
    ]
