# Generated by Django 3.1.5 on 2021-12-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0004_auto_20210603_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Hatırlatıcıya Abone Olanlar',
            },
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'Geri Bildirimler'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profiller'},
        ),
        migrations.AlterModelOptions(
            name='quizrecorder',
            options={'verbose_name_plural': 'Quiz kayıtları'},
        ),
        migrations.AlterModelOptions(
            name='shopproducts',
            options={'verbose_name_plural': 'Market Ürünleri'},
        ),
        migrations.AlterModelOptions(
            name='worddb',
            options={'verbose_name_plural': 'Database Kelimeleri'},
        ),
        migrations.AlterModelOptions(
            name='worden',
            options={'ordering': ['-create_time'], 'verbose_name_plural': 'İngilizce Kelimeler'},
        ),
        migrations.AlterModelOptions(
            name='wotden',
            options={'verbose_name_plural': 'Günün Kelimeleri'},
        ),
        migrations.AlterField(
            model_name='shopproducts',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
