# Generated by Django 3.1.4 on 2020-12-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0004_dailywords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyWords',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='word',
            new_name='english',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='translation',
            new_name='english',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='word',
            new_name='turkish',
        ),
        migrations.AddField(
            model_name='word',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
