# Generated by Django 3.1.5 on 2021-12-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0005_auto_20211219_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remindersubscription',
            name='email',
            field=models.CharField(max_length=35),
        ),
    ]
