# Generated by Django 3.1.4 on 2020-12-17 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0005_auto_20201216_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='turkish',
        ),
        migrations.CreateModel(
            name='WordTr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turkish', models.CharField(max_length=100)),
                ('word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_dict.word')),
            ],
        ),
    ]
