# Generated by Django 3.1.4 on 2020-12-17 18:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_dict', '0006_auto_20201217_2054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Word',
            new_name='WordEn',
        ),
    ]
