# Generated by Django 3.1.5 on 2021-12-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0006_auto_20211223_1337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReminderSubscription',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_registered_to_reminder',
            field=models.BooleanField(default=False),
        ),
    ]
