# Generated by Django 3.1.4 on 2020-12-17 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0007_auto_20201217_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordtr',
            name='word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turkish', to='my_dict.worden'),
        ),
    ]
