# Generated by Django 3.1.4 on 2020-12-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0008_auto_20201217_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordtr',
            old_name='word',
            new_name='english',
        ),
    ]
