# Generated by Django 3.1.4 on 2020-12-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0009_auto_20201217_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
