# Generated by Django 3.1.4 on 2020-12-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0010_search_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='worden',
            name='pronunciation',
            field=models.CharField(default=True, max_length=300),
            preserve_default=False,
        ),
    ]
