# Generated by Django 3.1.4 on 2020-12-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0011_worden_pronunciation'),
    ]

    operations = [
        migrations.AddField(
            model_name='worden',
            name='is_learned',
            field=models.BooleanField(default=False),
        ),
    ]
