# Generated by Django 3.1.4 on 2020-12-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0012_worden_is_learned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worden',
            old_name='pronunciation',
            new_name='audio',
        ),
    ]
