# Generated by Django 3.1.4 on 2020-12-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0013_auto_20201222_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='worden',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
