# Generated by Django 3.1.4 on 2020-12-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0014_worden_is_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='english',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
