# Generated by Django 3.1.4 on 2020-12-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0015_auto_20201224_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='worden',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
