# Generated by Django 3.1.4 on 2020-12-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0016_worden_is_starred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worden',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
