# Generated by Django 3.1.4 on 2020-12-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0017_auto_20201224_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worden',
            options={'ordering': ['-create_time']},
        ),
        migrations.AlterField(
            model_name='worden',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
