# Generated by Django 3.1.5 on 2021-01-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0018_auto_20201230_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worden',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
