# Generated by Django 3.1.5 on 2021-02-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0021_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_quiz_l_finished',
            new_name='is_quiz_learned_finished',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_quiz_unl_finished',
            new_name='is_quiz_unlearned_finished',
        ),
    ]
