# Generated by Django 3.1.5 on 2021-03-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0023_auto_20210301_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordoftheday',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
