# Generated by Django 3.1.5 on 2021-03-01 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0024_wordoftheday_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='WotdEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=100, null=True)),
                ('audio', models.CharField(max_length=300, null=True)),
                ('website', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WotdTr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turkish', models.CharField(max_length=100)),
                ('english', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wotd_turkish', to='my_dict.wotden')),
            ],
        ),
        migrations.DeleteModel(
            name='WordOfTheDay',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='english',
            new_name='search',
        ),
        migrations.AlterField(
            model_name='wordtr',
            name='english',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_turkish', to='my_dict.worden'),
        ),
    ]
