# Generated by Django 3.1.5 on 2021-03-01 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0025_auto_20210301_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordtr',
            name='english',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turkish', to='my_dict.worden'),
        ),
        migrations.AlterField(
            model_name='wotdtr',
            name='english',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turkish', to='my_dict.wotden'),
        ),
    ]
