# Generated by Django 3.1.5 on 2021-03-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0028_auto_20210302_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='profile',
            new_name='user',
        ),
    ]
