# Generated by Django 3.1.5 on 2021-03-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0029_auto_20210302_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='worden',
            name='is_in_reminder_list',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
