# Generated by Django 3.1.5 on 2021-03-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0030_auto_20210302_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='open_reminder_daily',
            field=models.BooleanField(default=False),
        ),
    ]
