# Generated by Django 3.1.5 on 2021-03-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0032_quizrecorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=50)),
            ],
        ),
    ]
