# Generated by Django 3.1.5 on 2021-03-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0033_worddb'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_quiz_db_finished',
            field=models.BooleanField(default=False),
        ),
    ]
