# Generated by Django 3.1.5 on 2021-03-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0034_profile_is_quiz_db_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizrecorder',
            name='is_db',
            field=models.BooleanField(default=False),
        ),
    ]
