# Generated by Django 3.1.5 on 2021-03-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0035_quizrecorder_is_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='worddb',
            name='is_in_reminder_list',
            field=models.BooleanField(default=False),
        ),
    ]
