# Generated by Django 3.1.5 on 2021-03-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0036_worddb_is_in_reminder_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reminder_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
