# Generated by Django 3.1.5 on 2021-03-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0037_profile_reminder_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reminder_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
