# Generated by Django 3.1.5 on 2021-04-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0039_auto_20210312_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizrecorder',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
