# Generated by Django 3.1.5 on 2021-04-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0040_quizrecorder_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='worden',
            name='is_new_in_reminder_list',
            field=models.BooleanField(default=False),
        ),
    ]
