# Generated by Django 3.1.5 on 2021-04-13 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_dict', '0041_worden_is_new_in_reminder_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250)),
                ('coin_value', models.IntegerField(default=0)),
                ('is_daily', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='coin',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AchievementTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achiev_1', models.BooleanField(default=False)),
                ('achiev_2', models.BooleanField(default=False)),
                ('achiev_3', models.BooleanField(default=False)),
                ('achiev_4', models.BooleanField(default=False)),
                ('achiev_5', models.BooleanField(default=False)),
                ('achiev_6', models.BooleanField(default=False)),
                ('achiev_7', models.BooleanField(default=False)),
                ('achiev_8', models.BooleanField(default=False)),
                ('achiev_9', models.BooleanField(default=False)),
                ('achiev_10', models.BooleanField(default=False)),
                ('achiev_11', models.BooleanField(default=False)),
                ('achiev_12', models.BooleanField(default=False)),
                ('achiev_13', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
