# Generated by Django 3.1.5 on 2021-04-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0042_auto_20210413_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='progress',
            field=models.IntegerField(default=1),
        ),
    ]
