# Generated by Django 3.1.5 on 2021-04-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0043_achievements_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='achievementtracker',
            name='achiev_1',
        ),
        migrations.RemoveField(
            model_name='achievementtracker',
            name='achiev_10',
        ),
        migrations.RemoveField(
            model_name='achievementtracker',
            name='achiev_11',
        ),
        migrations.RemoveField(
            model_name='achievementtracker',
            name='achiev_12',
        ),
        migrations.RemoveField(
            model_name='achievementtracker',
            name='achiev_13',
        ),
        migrations.RemoveField(
            model_name='achievementtracker',
            name='achiev_2',
        ),
        migrations.RemoveField(
            model_name='achievementtracker',
            name='achiev_3',
        ),
        migrations.RemoveField(
            model_name='achievementtracker',
            name='achiev_4',
        ),
        migrations.RemoveField(
            model_name='achievementtracker',
            name='achiev_5',
        ),
        migrations.RemoveField(
            model_name='achievementtracker',
            name='achiev_6',
        ),
        migrations.RemoveField(
            model_name='achievementtracker',
            name='achiev_7',
        ),
        migrations.RemoveField(
            model_name='achievementtracker',
            name='achiev_8',
        ),
        migrations.RemoveField(
            model_name='achievementtracker',
            name='achiev_9',
        ),
        migrations.AddField(
            model_name='achievementtracker',
            name='achiev_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievementtracker',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
