# Generated by Django 3.1.5 on 2021-04-14 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0044_auto_20210414_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementtracker',
            name='user',
        ),
        migrations.AddField(
            model_name='achievementtracker',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_dict.profile'),
        ),
    ]
