# Generated by Django 3.1.5 on 2021-04-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0045_auto_20210414_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievements',
            options={'verbose_name_plural': 'Başarılar'},
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Aramalar'},
        ),
        migrations.AddField(
            model_name='achievements',
            name='achiev_no',
            field=models.IntegerField(default=0),
        ),
    ]
