# Generated by Django 3.1.5 on 2021-04-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0048_auto_20210418_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementtracker',
            name='progress_max',
        ),
        migrations.AddField(
            model_name='achievements',
            name='progress_max',
            field=models.IntegerField(default=0),
        ),
    ]
