# Generated by Django 3.1.5 on 2021-04-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0049_auto_20210418_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievementtracker',
            old_name='progress',
            new_name='progress_percentage',
        ),
        migrations.AddField(
            model_name='achievementtracker',
            name='progress_current',
            field=models.IntegerField(default=0),
        ),
    ]
