# Generated by Django 3.1.5 on 2021-04-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0050_auto_20210418_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementtracker',
            name='progress_current',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='achievementtracker',
            name='progress_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
