# Generated by Django 3.1.5 on 2021-04-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0051_auto_20210418_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementtracker',
            name='progress_percentage',
        ),
        migrations.AddField(
            model_name='achievementtracker',
            name='progress_star',
            field=models.IntegerField(default=0),
        ),
    ]
