# Generated by Django 3.1.5 on 2021-04-22 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0052_auto_20210421_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='achiev_no',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='coin_value',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='is_daily',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='progress_max',
        ),
        migrations.CreateModel(
            name='AchievementDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250)),
                ('coin_value', models.IntegerField(default=0)),
                ('is_daily', models.BooleanField(default=False)),
                ('achiev_no', models.IntegerField(default=0)),
                ('progress_max', models.IntegerField(default=0)),
                ('ach_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_dict.achievements')),
            ],
        ),
    ]
