# Generated by Django 3.1.5 on 2021-04-22 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0053_auto_20210422_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementdetail',
            name='ach_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='my_dict.achievements'),
        ),
    ]
