# Generated by Django 3.1.5 on 2021-04-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0054_auto_20210422_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
