# Generated by Django 3.1.5 on 2021-04-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0055_shopproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproducts',
            name='type',
            field=models.TextField(default=''),
        ),
    ]
