# Generated by Django 3.1.5 on 2021-04-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0056_shopproducts_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproducts',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
