# Generated by Django 3.1.5 on 2021-05-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0057_auto_20210430_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproducts',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
