# Generated by Django 3.1.5 on 2021-05-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0058_shopproducts_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproducts',
            name='keyword',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
