# Generated by Django 3.1.5 on 2021-05-03 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0059_shopproducts_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproducts',
            name='keyword',
        ),
        migrations.CreateModel(
            name='ProductTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_dict.shopproducts')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_dict.profile')),
            ],
        ),
    ]
