# Generated by Django 3.1.5 on 2021-05-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0060_auto_20210503_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttracker',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
