# Generated by Django 3.1.5 on 2021-05-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0061_producttracker_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttracker',
            old_name='prof',
            new_name='profile',
        ),
    ]
