# Generated by Django 3.1.5 on 2021-05-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0063_auto_20210503_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproducts',
            name='keyword',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
