# Generated by Django 3.1.5 on 2021-05-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0064_shopproducts_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_background',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_navbar',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
