# Generated by Django 3.1.5 on 2021-05-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0067_auto_20210506_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproducts',
            name='bg_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
