# Generated by Django 3.1.5 on 2021-05-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0068_shopproducts_bg_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopproducts',
            old_name='bg_img',
            new_name='background_image',
        ),
    ]
