# Generated by Django 3.1.5 on 2021-05-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0069_auto_20210517_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproducts',
            name='background_image',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
