# Generated by Django 3.1.5 on 2021-05-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0071_auto_20210517_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopproducts',
            old_name='id',
            new_name='uuid',
        ),
    ]
