# Generated by Django 3.1.5 on 2021-05-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0072_auto_20210517_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproducts',
            name='uuid',
        ),
        migrations.AddField(
            model_name='shopproducts',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
