# Generated by Django 3.1.5 on 2021-05-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0074_auto_20210517_1335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopProducts',
        ),
    ]
