# Generated by Django 3.1.5 on 2021-05-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0076_shopproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproducts',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
