# Generated by Django 3.1.5 on 2021-05-17 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0077_auto_20210517_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproducts',
            name='id',
        ),
        migrations.AddField(
            model_name='shopproducts',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
