# Generated by Django 3.1.5 on 2021-05-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0078_auto_20210517_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproducts',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
