# Generated by Django 3.1.5 on 2021-05-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0079_auto_20210517_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopproducts',
            old_name='uuid',
            new_name='id',
        ),
    ]
