# Generated by Django 3.1.5 on 2021-05-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0080_auto_20210517_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproducts',
            name='id',
            field=models.UUIDField(default=1499, primary_key=True, serialize=False),
        ),
    ]
