# Generated by Django 3.1.5 on 2021-05-17 11:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0081_auto_20210517_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproducts',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
