# Generated by Django 3.1.5 on 2021-05-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0083_remove_shopproducts_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproducts',
            name='type',
            field=models.CharField(choices=[('clr', 'Renk'), ('bg-img', 'Arka plan resim'), ('music', 'Müzik')], default='Renk', max_length=15),
        ),
    ]
