# Generated by Django 3.1.5 on 2021-05-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0084_auto_20210517_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproducts',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
