# Generated by Django 3.1.5 on 2021-05-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0085_auto_20210517_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproducts',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='my_dict/static/img'),
        ),
    ]
