# Generated by Django 3.1.5 on 2021-05-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0086_auto_20210517_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproducts',
            name='keyword',
            field=models.CharField(default='', max_length=15),
        ),
    ]
