# Generated by Django 3.1.5 on 2021-05-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0089_auto_20210518_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttracker',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
