# Generated by Django 3.1.5 on 2021-05-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0092_auto_20210518_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_quiz_db_finished',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_quiz_learned_finished',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_quiz_unlearned_finished',
        ),
        migrations.AddField(
            model_name='profile',
            name='quiz_db_rights',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='quiz_l_rights',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='quiz_unl_rights',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shopproducts',
            name='type',
            field=models.CharField(choices=[('clr', 'Renk'), ('bg-img', 'Arka plan resim'), ('rights', 'Haklar')], default='Renk', max_length=15),
        ),
    ]
