# Generated by Django 3.1.5 on 2021-05-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0094_auto_20210526_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='quiz_db_rights',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='quiz_l_rights',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='quiz_unl_rights',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
