# Generated by Django 3.1.5 on 2021-05-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0095_auto_20210526_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('text', models.TextField(max_length=2500)),
            ],
        ),
    ]
