# Generated by Django 3.1.5 on 2021-05-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0096_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='lastname',
            new_name='isim',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='text',
            new_name='mesaj',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='soyisim',
        ),
    ]
