# Generated by Django 3.1.5 on 2021-06-02 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0098_auto_20210602_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttracker',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shopproducts',
            name='id',
        ),
        migrations.AlterField(
            model_name='producttracker',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shopproducts',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
