# Generated by Django 3.1.5 on 2021-06-03 12:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('my_dict', '0101_auto_20210603_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttracker',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='shopproducts',
            name='uuid',
        ),
        migrations.AddField(
            model_name='producttracker',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='shopproducts',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
